name: MATLAB CI

on:
  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]

  workflow_dispatch:

jobs:
  run-matlab-tests:
    runs-on: ubuntu-latest # Linux runner is generally fastest/cheapest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Run MATLAB unit tests
        uses: matlab-actions/run-tests@v2
        with:
          source-folder: .
          select-by-folder: 'test'
