name: MATLAB CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main/master branch
  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]

  # allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-matlab-tests:
    runs-on: ubuntu-latest # Linux runner is generally fastest/cheapest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Run MATLAB unit tests
        uses: matlab-actions/run-tests@v2 # Use the latest major version
        with:
          source-folder: . # Assumes class and test file are accessible from the root
          select-by-folder: 'test' # Runs all tests in the 'test' folder
